name: Deploy Streamlit App to Cloud Run

on: push

env:
  PROJECT_ID: capable-arbor-293714 # Replace with your Google Cloud Project ID
  REGION: us-central1 # Replace with your desired GCP region (e.g., us-central1)
  SERVICE_NAME: stock-recommendation-app # Must match the SERVICE_NAME used in manual steps
  IMAGE_REPO_NAME: stock-recommendation-app-repo # Must match the repo name from manual steps
  IMAGE_NAME: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPO_NAME }}/${{ env.SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.RECOMMENDATION_APP_GCP_SA_KEY_DEV }}

      - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_NAME }}:latest
          region: ${{ env.REGION }}
          allow_unauthenticated: true # Set to false if you want to restrict access
          port: 8080 # Streamlit's default port

      - name: Show Cloud Run URL
        run: echo "🚀 Streamlit app deployed to: ${{ steps.deploy.outputs.url }}"
